### ISSUE TITLE
SF7 nt working?

### ISSUE THREAD

**Issue by tigernnj** [Ideetron/RFM95W_Nexus#7]
i've been testing LoRaWAN_V31 example.

On LoRaWAN_V31.ino line 33 it says that this example transmits with Spreading factor 7.
After checking with iot.semtech server it shows as SF11 so i've searched RFM_Send_Package()  on RFM95_V21.cpp and found that it really is configured to SF11 (0xB4)
//Switch to SF7 CRC on payload on
  RFM_Write(0x1E,0xB4);

Now after changing register 0x1E to 0x74 (SF7) no more messages arrived to server.

This is not supposed to work with SF7? Am i missing something?

Thank you

**Comment by barthiddink** [comment]
Hi,
Yes, I've tested it today and you are right.There is a typo in the code.There might be some more..
Anyway, you need to set register 0x26 back to 0x04 (from. 0x0C).You only need to set 0x26 to 0x0C if you use SF11 and SF12.

Best regards Bart 

Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: tigernnj <notifications@github.com> Datum: 06-12-16  18:51  (GMT+01:00) Aan: Ideetron/RFM95W_Nexus <RFM95W_Nexus@noreply.github.com> Onderwerp: [Ideetron/RFM95W_Nexus] SF7 nt working? (#7) 
i've been testing LoRaWAN_V31 example.
On LoRaWAN_V31.ino line 33 it says that this example transmits with Spreading factor 7.

After checking with iot.semtech server it shows as SF11 so i've searched RFM_Send_Package()  on RFM95_V21.cpp and found that it really is configured to SF11 (0xB4)

//Switch to SF7 CRC on payload on

RFM_Write(0x1E,0xB4);
Now after changing register 0x1E to 0x74 (SF7) no more messages arrived to server.
This is not supposed to work with SF7? Am i missing something?
Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ideetron/RFM95W_Nexus","title":"Ideetron/RFM95W_Nexus","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Ideetron/RFM95W_Nexus"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"SF7 nt working? (#7)"}],"action":{"name":"View Issue","url":"https://github.com/Ideetron/RFM95W_Nexus/issues/7"}}}

**Comment by tigernnj** [comment]
thank you for your answer.

But can you elaborate a bit more?
On datasheet setting register 0x26 to 0x04 disables MobileNode bit, right? How is this related?
can't seem to find anything on datasheet...

kind regards

**Comment by barthiddink** [comment]
Hi,
Check page 114 of the data sheet.Low datarate optimize.
This bit must be set if the bit length exceeds 16ms.This is only the case for SF11 and 12.
Google SX1276 and the first hit you will find the right PDF.
Regards, Bart 
Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: tigernnj <notifications@github.com> Datum: 06-12-16  20:29  (GMT+01:00) Aan: Ideetron/RFM95W_Nexus <RFM95W_Nexus@noreply.github.com> Cc: Bart Hiddink <bart@ideetron.nl>, Comment <comment@noreply.github.com> Onderwerp: Re: [Ideetron/RFM95W_Nexus] SF7 nt working? (#7) 
thank you for your answer.
But can you elaborate a bit more?

On datasheet setting register 0x26 to 0x04 disables MobileNode bit, right? How is this related?

can't seem to find anything on datasheet...
kind regards

**Comment by tigernnj** [comment]
Hi,

Ok. I was looking only on RFM95 datasheet.

So register 0x26 should be 0x04 also for RFM_Receive() - downlink

I've corrected it but dowlink still not working.

Thank you

**Comment by barthiddink** [comment]
Hi Nelson,

Nah, use the SX1276, that is the RF chip on the RFM95W.
But please keep this our secret! ;)

Downlink is on SF9, so 0x26 should be 0x04, or default (=0x04).

The rest is a timing issue.

Please read issue #5.

Best regards,
Bart

Nelson Jesus schreef op 2016-12-07 12:33:
> Hi,
> 
> Ok. I was looking only on RFM95 datasheet.
> 
> So register 0x26 should be 0x04 also for RFM_Receive() - downlink
> 
> I've corrected it but dowlink still not working.
> 
> Thank you
